# Generated by Django 5.0.3 on 2024-03-24 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_options_alter_product_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id', 'name'), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
